$('body')
    .margin(0)
    .padding(0)
    .height('300vh')
    .fontFamily('system-ui')

$('#header')
    // style header
    .position('sticky')
    .top(0)
    .maxWidth('100%')
    .height(60)
    .color('#000')
    .transition(0.5)
    .display('flex')
    .alignItems('center')
    .padding('0 70px')
    // add logo container div & style it
    .insert('div')
    .setId('logoContainer')
    .width(100)
    .height('100%')
    .position('relative')
    // add logo img & style it
    .insert('img')
    .setId('logoImageColored')
    .addAttr('src', 'https://d1yei2z3i6k35z.cloudfront.net/4555433/64dc0776841e4_sticky-menu-colored-logo.png')
    .width('100%')
    .position('absolute')
    .transition(0.5)
    .left(0)
    .top(0)
    .parent()
    .insert('img')
    .setId('logoImageWhite')
    .addAttr('src','https://d1yei2z3i6k35z.cloudfront.net/4555433/64dc0781ef611_sticky-menu-white-logo.png')
    .opacity(0)
    .transition(0.5)
    .width('100%')
    .position('absolute')
    .left(0)
    .top(0)
    .parent(2)
    // add menu container div & style it
    .insert('div')
    .setId('Menu-container')
    .width('100%')
    // .color('#000')
    .transition(0.3)
    // add ul element and style it
    .insert('ul')
    .justifyContent('center')
    .listStyle('none')
    .display('flex')
    // add li element and style it
    .insert('li')
    .margin('0 10px')
    .text('tab 1')
    .parent()
    // add li element and style it
    .insert('li')
    .margin('0 10px')
    .text('tab 2')
    .parent()
    // add li element and style it
    .insert('li')
    .margin('0 10px')
    .text('tab 3')
    .parent()
    // add li element and style it
    .insert('li')
    .margin('0 10px')
    .text('tab 4')
    .parent()

document.addEventListener('scroll', _ => {
    // window.scrollY > 90 ? document.querySelector('#header').classList.add('scrolled') : document.querySelector('#header').classList.remove('scrolled');
    if (window.scrollY > 90) {
        $('#header')
        .background('#001c64')
        .color('#fff')
        $('#logoImageWhite')
        .opacity(1)
        $('logoImageColored')
        .opacity(0)
    } else {
        $('#header')
        .background('transparent')
        .color('#000')
        $('#logoImageWhite')
        .opacity(0)
        $('logoImageColored')
        .opacity(1)
    }
})